// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuhgbMfD0OIRyJi3ezUqaMuqEd_ypAS4g',
    appId: '1:137743040138:web:fc218d8e85a6af24a73773',
    messagingSenderId: '137743040138',
    projectId: 'e-shop-iti',
    authDomain: 'e-shop-iti.firebaseapp.com',
    storageBucket: 'e-shop-iti.appspot.com',
    measurementId: 'G-S49HKFM4Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQm2Tyaspup0ws9ZTZ6f24Yq-9eUc5hw',
    appId: '1:137743040138:android:23f09a4421feb347a73773',
    messagingSenderId: '137743040138',
    projectId: 'e-shop-iti',
    storageBucket: 'e-shop-iti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUIONBIz4OkbJG3Z05QqTtuBVYQ_BwCU',
    appId: '1:137743040138:ios:ca3396a4957e77e2a73773',
    messagingSenderId: '137743040138',
    projectId: 'e-shop-iti',
    storageBucket: 'e-shop-iti.appspot.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUIONBIz4OkbJG3Z05QqTtuBVYQ_BwCU',
    appId: '1:137743040138:ios:ca3396a4957e77e2a73773',
    messagingSenderId: '137743040138',
    projectId: 'e-shop-iti',
    storageBucket: 'e-shop-iti.appspot.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuhgbMfD0OIRyJi3ezUqaMuqEd_ypAS4g',
    appId: '1:137743040138:web:df66b20a76364bd2a73773',
    messagingSenderId: '137743040138',
    projectId: 'e-shop-iti',
    authDomain: 'e-shop-iti.firebaseapp.com',
    storageBucket: 'e-shop-iti.appspot.com',
    measurementId: 'G-4PQ1TP98P6',
  );
}
